export const INITIAL_CHECKPOINT_LOCATION_CONSTANT = 'System';
export const INITIAL_CHECKPOINT_MESSAGE_CONSTANT =
  'Unit registered in the system';

export const INVALID_STATE_TRANSITION_ERROR_CODE_CONSTANT =
  'INVALID_STATE_TRANSITION';
export const UNIT_NOT_FOUND_ERROR_CODE_CONSTANT = 'UNIT_NOT_FOUND';
