export enum UNIT_STATE_ENUMERATION {
  CREATED = 'CREATED',
  PICKED_UP = 'PICKED_UP',
  IN_TRANSIT = 'IN_TRANSIT',
  AT_FACILITY = 'AT_FACILITY',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  PICKED_UP_EXCEPTION = 'PICKED_UP_EXCEPTION',
  IN_TRANSIT_EXCEPTION = 'IN_TRANSIT_EXCEPTION',
  AT_FACILITY_EXCEPTION = 'AT_FACILITY_EXCEPTION',
  OUT_FOR_DELIVERY_EXCEPTION = 'OUT_FOR_DELIVERY_EXCEPTION',
}
